- player/ad-scheduling/js/script.js
Issue: https://github.com/bitmovin/dashboard/issues/1119
Description: Removed default ad being set always on pre-roll, fixed `persistent` typo
> Removed default ad in config

- player/vr-360/css/style.css
- player/vr-360/js/script.js
Issue: https://bitmovin.atlassian.net/browse/PW-4659
Currently iOS devices cannot play our VR-360 demo.
This PR excludes iOS devices and shows the message This demo is not currently available on iOS as we’re working to enhance this VR/360 demo. Please get in touch if you’d like to learn more. instead.
A separate web player issue will be created that deals with investigation and implementation of a fix.
> Exclude iOS devices from vr demo

- player/drm/css/style.css
The DRM demo does not render the video after the content has been started for a Playready stream. This has been observed on Chromium Edge running on Windows. 
The root cause for this issue is due to the border-radius manipulating the video element. Playready streams do not allow manipulation of the video element and they directly stop rendering due to this styling change.
Here I force the border-radius from the container and video element to always have no border-radius to allow video to be rendered.
> Fix Playready DRM demo not rendering video content due to border-radius style property

- player/vr-360/css/style.css
- player/vr-360/js/script.js
Re-enable the VR demo on iOS devices after it has been disabled in https://github.com/bitmovin/demos/pull/48. The underlying issue that broke VR playback will be fixed in Player v8.70.0.
**This branch shall not be merged before v8.70.0 was released.**
> Re-enable VR demo on iOS devices

- player/ad-event-verification-omsdk/index.html
- player/ad-event-verification-omsdk/js/script.js
If IE or Edge 18 is used we're now
- showing a message saying that the demo is not supported
- hiding the player and event log but still show getting started guide
--- 
Also: 
- Fixed self-closing `<hr>` and `<input>` tags in `index.html`
- Removed usage of template strings and arrow functions
> Disable Open Measurement SDK ad verification demo on IE and Edge browsers

- player/ad-scheduling/index.html
- player/ad-scheduling/js/script.js
This aligns the ad scheduling demo with the ad tag types that are currently supported in our player: https://bitmovin.com/docs/player/api-reference/web/web-sdk-api-reference-v8#/player/web/8/docs/enums/advertising.adtagtype.html
Changes:
- Remove legacy ad type "IMA"
- Exchange asset for VPAID, as it would always return an empty tag
- Pass the correct ad tag type to the player (`vmap` for vmap, `vast` for vpaid)
> Fix Ad Scheduling Demo

- player/stream-test/js/script.js
This fixes ad scheduling on the [stream test demo](https://bitmovin.com/demos/stream-test), which does not work as expected atm:
- Some ads to not work because the manifest requests return empty VAST
- The "Delete"  button to remove an ad does not work
- "IMA" is not a valid ad tag type anymore
Changes in this PR:
- Fix the "Delete" button by assigning an event listener instead of using the `onclick` attribute
- Align the ad tag types with the ones that are currently supported in our player: https://bitmovin.com/docs/player/api-reference/web/web-sdk-api-reference-v8#/player/web/8/docs/enums/advertising.adtagtype.html
- Replace ad manifest URLs with working ones
- Pass the correct ad tag type to the player (specifically, `vast` for vpaid - since [vpaid is …
> Fix ad scheduling on "Stream Test" demo

- analytics/analytics-bitrate-ladder-validator/info.json
- player/drm/index.html
- player/drm/info.json
- player/native-sdks/index.html
- player/stream-test/index.html
- player/stream-test/info.json
This PR updates URLs leading to the Android demo-app in the corresponding demos and updates priority of popular demos so they appear on top of the demos-overview.
> Update demo priorities and android links

- player/stream-test/css/style.css
Problem:
Playready DRM streams were not working on the stream-test demo page in (Chromium-based) Edge due to the CSS border-radius above the video and how the Playready video rendering pipeline workds.
Resolution:
Remove CSS border-radius on elements above the video.
> Fix Playready DRM playback in stream-test demo

- player/ad-event-verification-omsdk/index.html
- player/ad-event-verification-omsdk/page.html
As of version `8.81.0` the OMSDK lib files are part of the player bundle so we can remove these.
https://bitmovin.com/docs/player/releases/web/web-8-81-0
> Remove OMSDK lib files

- player/player-ui-styling/index.html
Align the button colors with what the buttons do.
Makes the `Orange Seek Bar` button orange/yellow, and the `Toggle Big Seek Bar` button gray.
Currently, it's the other way around, which is annoying :D https://bitmovin.com/demos/player-ui-styling
> Fix button colors in UI styling demo

- encoding/multi-codec-streaming/js/demo.js
- player/drm/index.html
- player/drm/js/script.js
- player/stream-test/index.html
Based on [SOL-2888](https://bitmovin.atlassian.net/browse/SOL-2888):
1. Changes to multi-codec demo: Added logic to detect supported Media Type on Edge, since current logic assigned a hardcoded HEVC. this is not correct for Edge on MAC.
2. Updated Font-Awesome brands styles to be compliant with latest version and to show newest icon for Edge.
Changed the CDN url for Font-awesome on parent project (demo-framework) added a separate PR
> SOL-2888 Updating FA styles and adding logic to detect supported codec

- player/drm/demo.js
- player/drm/js/script.js
- player/stream-test/js/script.js
The currently used License Server was missing CORS headers, leading to failing license requests. Using a different license server fixes this issue.
> Replace license server url to fix CORS errors

- encoding/av1-break-even-calculator/index.html
- encoding/av1-break-even-calculator/js/av1-break-even-calculator.js
This PR will improve the "AV1 break-even calculator" form the encoding demos: https://bitmovin.atlassian.net/browse/EN-11519
- improve copy text for description and footnote formula
- enable 4-digit dollar inputs, e.g. "0.0123$"
- remove "ingress cost" input
- remove Per-Title from factors and formula
- structure Calculation multipliers table into factors
Relates to https://github.com/bitmovin/demos/pull/92
> fix(EN-11519): improve AV1 break-even calculator

- player/custom-adaptation/js/script.js
Missing `var` causes an error when because of JS' `strict mode` and breaks the demo. Adding it in this PR to make the demo work again.
> Add missing `var` to avoid error in `strict` mode

- player/stream-test/css/style.css
Following up on https://github.com/bitmovin/demos/pull/102.
Fixes
to be
> Fix player appearance on Stream Test page

- player/drm/demo.js
- player/drm/js/script.js
- player/stream-test/js/script.js
PlayReady license requests to the URLs that we currently use are failing with an internal server error.
There are updated test server endpoints available: https://testweb.playready.microsoft.com/#march-15th-2017-migration-of-the-old-test-servers
This PR replaces all legacy `playready.directtaps.net` LA URLs to the updated `test.playready.microsoft.com`.
> [untracked] Migrate PlayReady LA URLs to new servers.

- player/low-latency-streaming/css/style.css
- player/low-latency-streaming/index.html
- player/low-latency-streaming/js/script.js
Since we now have a way to influence the players behavior when it comes to choosing the quality in LL environments, we decided to update the LL demo to include it.
BigScreen:
Smaller Screen:
> [PW-10478] Quality stability slider

- player/low-latency-streaming/js/script.js
The latency mode was always displayed as `1` since it only reacted to PlaybackSpeed changes.
The player does not expose the playback speed changes it does due to LowLatency mode changing. So I changed it to actually listen to the `LatencyModeChanged` event and display one of the modes:
- `catchup`
- `fallback`
- `idle`
- `suspended`
> Fix latency mode display

- player/low-latency-streaming/index.html
The initial latency mode was still displayed as `1`. When the first LatencyModeChanged event comes it reports switching `from` "suspended" to x, so I updated the initial value to represent the `suspended` state.
> Fix initial latency mode

- player/ad-scheduling/js/script.js
- player/stream-test/js/script.js
Update VPAID ad url to one from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags
The existing URL does not work anymore and fails with a `404` on the creative.
> Update VPAID ad URL

- player/drm/js/script.js
The DRM demo is not working on safari browser as it picks the wrong unsupported source(Dash with Fairplay).
This PR picks HLS source by default when safari browser is detected.
> Default HLS DRM source on Safari

- player/stream-test/index.html
Stream test source uses Dash by default that is not supported on iOS and demo does not work.
HLS source is now selected as default.
> Default HLS source in stream test demo

- player/sgai/js/script.js
The current main content for our SGAI / HLS Interstitial demo displays a green screen with a timestamp. It would be nicer to have actual content playing back.
This PR introduces an HLS stream that has the `AdBlendr` HLS Interstitials in, but uses _Art of Motion_ as main content.
> [untracked] Use AoM for main content
